name: Test bravis scraper
on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run bravis scraper
        run: python bravis.py
      - name: Commit and push JSON file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bravis.json
          git commit -m "Update bravis.json from GitHub Actions" || exit 0
          git push
